export default {
    booking_date:'Fecha de reserva',
    trip_start_time:'Hora de inicio del viaje',
    trip_end_time:'Hora de finalización del viaje',
    customer_name:'Nombre del cliente',
    car_type:'Configurar Servicio por Ciudad',
    vehicle_no:'Número de vehículo',
    pickup_address:'Dirección de recogida',
    drop_address:'Dirección de destino',
    assign_driver:'Asignar conductor',
    booking_status:'Estado de la reserva',
    trip_cost:'Coste del viaje',
    discount_ammount:'Importe de descuento',
    payment_status:'Estadus del pago',
    payment_mode:'Método de pago',
    booking_text:'Reservas',
    image:'Imagen',
    name:'Nombre',
    rate_per_km:'Tarifa por kilómetro',
    rate_per_hour:'Tarifa por hora',
    min_fare: 'Tarifa mínima',
    convenience_fee:'Tarifas de Servicio',
    convenience_fee_percent:'Tarifas de Servicio (%)',
    today_text:'Hoy',
    gross_earning:'Ingresos brutos',
    admin_convenience_fee:'Nuestras ganancias',
    this_month_text:'Mes',
    total:'Total',
    real_time_driver_section_text:'Conductores en tiempo real',
    allow_location:'Permitir ubicación para el mapa en tiempo real',
    sign_in:'Iniciar sesión',
    email_address:'Dirección de correo electrónico',
    password:'Contraseña',
    sign_in_error:'Error de inicio de sesión. Compruebe el correo electrónico y la contraseña. ',
    device_type:'Tipo de dispositivo',
    user_type:'Tipo de usuario',
    title:'Titulo',
    body:'Cuerpo',
    push_notification_title:'Notificaciones push',
    promo_name:'Nombre de la promoción',
    description:'Descripción',
    promo_type:'Tipo de promoción',
    promo_discount_value:'Valor de descuento promocional',
    max_limit:'Valor límite máximo',
    min_limit:'Recuento mínimo de pedidos',
    start_date:'Fecha de inicio (dd/mm/aaaa)',
    end_date:'Fecha de finalización (dd/mm/aaaa)',
    promo_usage:'Límite de uso de promociones',
    promo_used_by:'Promoción utilizada por',
    promo_offer:'Promo y ofertas',
    refferal_bonus:'Bono de referido',
    submit:'Enviar',
    update_failed:'Actualización fallida',
    first_name:'Nombre',
    last_name:'Apellido',
    email:'Email',
    mobile:'Móvil',
    profile_image:'Imagen de Perfil',
    vehicle_model:'Modelo de vehículo',
    account_approve:'Cuenta aprobada',
    driver_active:'Estado activo del conductor',
    lisence_image:'Imagen de licencia',
    vehicle_number:'Número de Placa',
    wallet_balance:'Saldo en Billetera',
    signup_via_refferal:'Registrarse por recomendación',
    refferal_id:'Id de referencia',
    all_user:'Todos los usuarios',
    notification_sent:' Notificaciones enviadas.',
    notification_sent_failed:'Error al enviar la notificación.',
    no_user_match:'No hay usuarios coincidentes',
    no_user_matching:'No se encontraron usuarios que coincidan con su selección.',
    dashboard_text:'Dashboard',
    user:'Usuarios',
    booking_history:'Historial de reservas',
    promo:'Promociones',
    logout:'Cerrar sesión',
    driver_earning:'Historial de ganancias del conductor',
    earning_amount:'Importe de ganancias',
    driver_name:'Nombre del conductor',
    driver_image:'Imagen del conductor',
    months:'Meses',
    year:'Años',
    vehicle_type:'Número de placa',
    lisence_no:'Número de licencia',
    booking_discount_earning:'Descuento de reserva',
    trip_cost_driver_share:'Costo del viaje / participación del conductor',
    Gross_trip_cost:"Coste bruto del viaje",
    Discounts:"Descuentos",
    Customer_paid:"Cliente pagado",
    Profit:"Beneficio (pagado por el cliente - Coste del viaje)",
    earning_reports:'Ganancias',
    cash_payment_amount:'Importe del pago en efectivo',
    card_payment_amount:'Importe del pago con tarjeta',
    wallet_payment_amount:'Importe del pago con Billetera',
    payment_getway:'Pasarela de pago'
}